version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - ./:/var/lib/drone/
    restart: always
    environment:
      - DRONE_HOST=https://559e3faa.ngrok.io
      - DRONE_OPEN=true
      - DRONE_SECRET=drone-workshop
      - DRONE_ADMIN=appleboy

      # GitLab Config
      - DRONE_GITLAB=true
      - DRONE_GITLAB_CLIENT=ac69d05250aba17d67b1c5ebb05dbbc24c4a83420e8865abd33ea7647ed0c078
      - DRONE_GITLAB_SECRET=05fa6a44bfa381b128331dcfb8942c978e15d7f9db3eaee35b904fb251fbd2a3
      - DRONE_GITLAB_URL=https://gitlab.com

  drone-agent:
    image: drone/agent:0.8
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=drone-workshop
      - DRONE_MAX_PROCS=3
